# Device
device: cuda:0

# Data
dataset_path: ./data
batch_size: 128

# Optimizer
lr: 0.01
client_optimizer: sgd
sgd_momentum: 0.9
wd: 0.0005

# Learning rate scheduler
lr_scheduler: MultiStepLR
steplr_milestones:
  - 50
  - 75
steplr_gamma: 0.1

# Misc
num_workers: 4
pin_memory: True
non_blocking: True
prefetch: False
amp: False
frequency_save: 0
random_seed: 0
epochs: 100
